- name: Run Tweet Bot
  env:
 
    TWEETER_API_KEY: ${{ secrets.TWEETER_API_KEY }}
    TWEETER_API_SECRET: ${{ secrets.TWEETER_API_SECRET }}
    TWEETER_ACCESS_TOKEN: ${{ secrets.TWEETER_ACCESS_TOKEN }}
    TWEETER_ACCESS_SECRET: ${{ secrets.TWEETER_ACCESS_SECRET }}
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  run: |
    python main.py || echo "Script failed, check logs"
